openapi: '3.0.2'
info:
  version: 1.0.0
  title: Example

servers:
  - url: /v1

paths:
  /ping:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ping'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
        '400':
          description: Bad Request

components:
  schemas:
    Ping:
      type: object
      properties:
        id:
          type: string
      required:
        - id
    Pong:
      type: object
      properties:
        id:
          type: string
      required:
        - id
